version: '3.3'
services:
  blog-mysql:
    image: mysql:8.0.26
    network_mode: "host"
    container_name: blog-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d

  blog-client:
    build: ./Client
    command: npx nodemon -w dist ./client.js
    network_mode: "host"
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./Client:/app
    container_name: blog-client
    depends_on:
      - blog-service

  blog-service:
    build: ./Serrver
    command: python app.py --log-level=DEBUG
    network_mode: "host"
    volumes:
      - ./Server:/app/Server
    ports:
      - "3000:3000"
    restart: always
    container_name: blog-service
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MYSQL_DATABASE=blog
      - MYAQL_PASSWORD=blog
    depends_on:
      - blog-minio
      - blog-mysql

  blog-minio:
    image: minio/minio
    network_mode: "host"
    container_name: blog-minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio:/data
    restart: always
    command: server /data --console-address ":9001"